### PR TITLE
device-specific test failures (tests failing)

### PR DESCRIPTION
**Pull request by czechboy0**

### CODE REVIEW

**Comment by buildasaur** [comment]
## Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/903197d94f3b8d3c37fea94113f36443/903197d94f3b8d3c37fea94113f36af5)

_Duration_: 47 seconds
_Result_: All 4 tests passed, but please **fix 1 warning**.

**Comment by buildasaur** [comment]
## Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/4ddb911d66323b2802add63c73000105/5fd8a6d96807de1abd110aae15000011)

_Duration_: 1 minute and 34 seconds
_Result_: **Perfect build!** All 1 test passed. :+1:

**Comment by buildasaur** [comment]
## Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/988772e2f2b47c8fba527ed14f2fdf25/988772e2f2b47c8fba527ed14f2ffeee)

_Duration_: 21 seconds
_Result_: **Perfect build!** All 1 test passed. :+1:

**Comment by buildasaur** [comment]
## Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/988772e2f2b47c8fba527ed14f313261/988772e2f2b47c8fba527ed14f314885)

_Duration_: 1 minute and 37 seconds
_Result_: **Build failed 1 test** out of 4

**Comment by czechboy0** [comment]
me too

**Comment by buildasaur** [comment]
## Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/1413f8578e54c3d052b8121a25404789/1413f8578e54c3d052b8121a254068ac)

_Duration_: 4 seconds
_Result_: **-1 error, failing state: trigger-error**

**Pull request closed without merging**
